### ISSUE TITLE
libarcsoft_face_engine_jni.so文件问题

### ISSUE THREAD

**Issue by jackyting825** [itboyst/ArcSoftFaceDemo#1]
libarcsoft_face_engine_jni.so这个文件sdk没有的呀.我选择的是ArcFace v2.0 linuxx64的SDK,lib目录下就只有libarcsoft_face_engine.so和libarcsoft_face.so这2个文件.然后将这2个文件放到jdk的bin目录下依然会提示java.lang.UnsatisfiedLinkError: no arcsoft_face_engine_jni in java.library.path..请问一下是什么原因?
--

**Comment by itboyst** [comment]
去官网上下载linux64 java语言的就有jni文件

发自我的 iPhone

**Comment by jackyting825** [comment]
> 去官网上下载linux64 java语言的就有jni文件 发自我的 iPhone
> […](#)
> 在 2018年12月22日，10:15，jackyting825 ***@***.***> 写道： libarcsoft_face_engine_jni.so这个文件sdk没有的呀.我选择的是ArcFace v2.0 linuxx64的SDK,lib目录下就只有libarcsoft_face_engine.so和libarcsoft_face.so这2个文件.然后将这2个文件放到jdk的bin目录下依然会提示java.lang.UnsatisfiedLinkError: no arcsoft_face_engine_jni in java.library.path..请问一下是什么原因? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

多谢,我记得前段时间去创建应用的时候没有java语言可以选择的.所以当时只有C++.刚刚我新建应用发现有Java版本的了.不知道是不是最近新出的
